name: Push main to uktrade/rowan-test-mirror-repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-main:
    runs-on: ubuntu-latest
    # Optional: avoid overlapping pushes if multiple commits land in quick succession
    concurrency:
      group: push-main
      cancel-in-progress: true

    steps:
      # 1) Checkout only the main branch (no tags/history needed)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Load your SSH deploy key from the source repo's secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}


      # 4) Push main → main to the destination repo
      - name: Push main to destination
        env:
          DEST_SSH_URL: git@github.com:uktrade/rowan-test-mirror-repo.git
          DEST_BRANCH: main
        run: |
          git push ${DEST_SSH_URL} ${DEST_BRANCH} 
