name: Push main to uktrade/rowan-test-mirror-repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-main:
    runs-on: ubuntu-latest
    # Optional: avoid overlapping pushes if multiple commits land in quick succession
    concurrency:
      group: push-main
      cancel-in-progress: true

    steps:
      # 1) Checkout only the main branch (no tags/history needed)
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      # 2) Load your SSH deploy key from the source repo's secrets
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}

      # 3) Trust GitHub's host key (adjust if your destination host differs)
      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # 4) Push main → main to the destination repo
      - name: Push main to destination
        env:
          DEST_SSH_URL: git@github.com:uktrade/rowan-test-mirror-repo.git
          DEST_BRANCH: main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add dest "$DEST_SSH_URL"

          # Non-forced push (safe). Use --force-with-lease if you need to overwrite.
          git push dest HEAD:refs/heads/${DEST_BRANCH}

          # If you ever want to push tags as well, uncomment:
          # git push --tags dest
