name: mirror repo

on:
    push:
      branches:
        - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test pull mirror repo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
            git config --global
            url."https://x-access:${{ secrets.PAT }}@github.com"
            .insteadOf https:github.com/
            git clone http://github.com/uktrade/rowan-test-mirror-repo.git
      #   env:
      # - name: Add mirror
      #   run: |
      #       git remote add mirror \
      #       https://x-access:${{ secrets.PAT }}@github.com/uktrade/rowan-test-mirror-repo.git
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
      # - name: Push main to mirror
      #   run: |
      #       git push mirror main:main --force
      # - name: Push to Mirror
      #   run: git push --mirror "https://x:$GITHUB_TOKEN@github.com/uktrade/rowan-test-mirror-repo"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
